[package]
name = "std"
version = "0.1.0"

[lib]
path = "std.rs"

[dependencies.conv]
git = "https://github.com/DanielKeep/rust-conv.git"
rev = "b03427a13b3f92fb8f65c80822e056a98cdce036"
default_features = false
