[package]
name = "std"
version = "0.1.0"

[lib]
path = "std.rs"

[dependencies.conv]
git = "https://github.com/AveryOS/rust-conv.git"
rev = "31f59a4f8b15454d04a0c4127e6c406ba1f7f1c9"
features = ["no_std"]
