notifications:
  email: false
git:
  submodules: false
os: linux
env:
  - DUMMY_JOB=1
script: echo dummy job
matrix:
  exclude:
    env: TRAVIS_DUMMY=1
  include:
  - env:
    - AVERY_BUILD=RELEASE CC=clang-3.7 CXX=clang++-3.7
    addons:
     apt:
       sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.7
       packages:
       - g++-4.8
       - clang-3.7
       - ninja-build
       - texinfo   
    cache:
      timeout: 1000
      directories:
      - build/pkgs/meta
      - build/pkgs/install
    script: rake
  - env:
    - AVERY_BUILD=DEBUG CC=clang-3.7 CXX=clang++-3.7
    addons:
     apt:
       sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.7
       packages:
       - g++-4.8
       - clang-3.7
       - ninja-build
       - texinfo   
    cache:
      timeout: 1000
      directories:
      - build/pkgs/meta
      - build/pkgs/install
    script: rake
  - script: rake test_verifier
    language: rust
    rust: nightly
    env:
    - VERIFIER=1
