notifications:
  email: false
git:
  submodules: false
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   - ninja-build
   - texinfo
env:
  CC: gcc-4.8
  CXX: g++-4.8
language: ruby
cache:
  timeout: 1000
  directories:
  - vendor/cache
