notifications:
  email: false
git:
  submodules: false
matrix:
  include:
    - os: linux
      env:
        CC: clang
        CXX: clang++
      addons:
       apt:
         sources:
         - ubuntu-toolchain-r-test
         packages:
         - gcc-4.8
         - g++-4.8
         - ninja-build
         - texinfo
language: ruby
cache:
  timeout: 1000
  directories:
  - vendor/cache
