[package]
name = "avery"
version = "0.1.0"

[lib]
path = "kernel.rs"
crate-type = ["staticlib"]

[dependencies]
clippy = { git = "https://github.com/Manishearth/rust-clippy.git", rev = "973ae82d72368401c237b0e8f62012c8ac28df70" }
rlibc = "0.1.5"
elfloader = { path = "../verifier/rust-elfloader" }
assembly = { path = "../vendor/asm" }
std = { path = "std" }
allocator = { path = "allocator" }
