[package]
name = "verifier"
version = "0.1.0"
authors = ["John Kåre Alsaker <john.kare.alsaker@gmail.com>"]

[dependencies]
byteorder = "0.4.2"

[dependencies.elfloader]
path = "rust-elfloader"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"